[workspace]
members = ["gui"]

[package]
name = "vsd"
version = "0.1.2"
edition = "2021"
description = "Command line program to download HLS video from websites and m3u8 links."
repository = "https://github.com/clitic/vsd"
documentation = "https://docs.rs/vsd"
categories = ["command-line-interface"]
license = "MIT"
readme = "README.md"
exclude = ["images"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.1", features = ["derive"] }
headless_chrome = "0.9"
kdam = "0.1.7"
m3u8-rs = "4.0"
openssl = "0.10"
regex = "1.5"
requestty = "0.3.0"
reqwest = { version = "0.11", features = ["blocking", "cookies"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
terminal_size = "0.2"
threadpool = "1.0"

[features]
default = ["reqwest/native-tls-vendored"]
rustls-tls = ["reqwest/rustls-tls"]