[package]
name = "vsd"
version = "0.1.3"
description = "Command line program to download HLS video from websites and m3u8 links"
authors = ["clitic <clitic21@gmail.com>"]
repository = "https://github.com/clitic/vsd"
documentation = "https://docs.rs/vsd"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["m3u8"]
categories = ["command-line-utilities"]
exclude = ["docs", "images"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
headless_chrome = "0.9"
kdam = "0.2"
m3u8-rs = "5"
openssl = "0.10"
regex = "1"
requestty = "0.4.1"
reqwest = { version = "0.11", features = ["blocking", "cookies"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
threadpool = "1"

[features]
default = ["reqwest/native-tls-vendored"]
rustls-tls = ["reqwest/rustls-tls"]
